name: game_app
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.2
  provider: ^6.0.5
  cached_network_image: ^3.2.3
  percent_indicator: ^4.2.3
  flutter_html: ^3.0.0-beta.2
  intl: ^0.18.1
  url_launcher: ^6.1.12
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  fonts:
    - family: Helvetica
      fonts:
        - asset: assets/font/Helvetica.ttf

  assets:
    - assets/images/types.png
